drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
