drop table if exists Client CASCADE 
drop table if exists Client CASCADE 
drop table if exists Client CASCADE 
drop table if exists Client CASCADE 
drop table if exists Client CASCADE 
drop table if exists Client CASCADE 
drop table if exists Client CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Client CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Costumer CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Costumer CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Costumer CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Costumer CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Costumer CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Costumer CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Costumer CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Costumer CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Costumer CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Costumer CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Costumer CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Costumer CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Costumer CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Costumer CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Costumer CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Costumer CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Costumer CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Costumer CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Costumer CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Customer CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists Customer CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
drop table if exists CUSTOMER CASCADE 
drop table if exists Nutritionist CASCADE 
drop table if exists Store CASCADE 
